//RESPUESTAS
export const NUEVA_RESPUESTA = 'NUEVA_RESPUESTA';
export const ACTUALIZAR_RESPUESTA = 'ACTUALIZAR_RESPUESTA';
export const GENERAR_RESPUESTAS = 'GENERAR_RESPUESTAS';

//SELECCION TIPO FORMULARIO
export const FORMULARIO_SELECCION = 'FORMULARIO_SELECCION'
export const FORMULARIO_OPCIONES = 'FORMULARIO_OPCIONES'

//DATOS GENERALES
export const DATOSGENERALES_CUIT = 'DATOSGENERALES_CUIT'

//ESTABLECIMIENTO
export const ESTABLECIMIENTO_SELECCION = 'ESTABLECIMIENTO_SELECCION'

//GREMIOS
export const GREMIO_NUEVO = 'GREMIO_NUEVO'
export const GREMIO_ACTUALIZAR = 'GREMIO_ACTUALIZAR'

//RESPONSABLES
export const RESPONSABLE_NUEVO = 'RESPONSABLE_NUEVO'
export const RESPONSABLE_ACTUALIZAR = 'RESPONSABLE_ACTUALIZAR'

//CONTRATISTA
export const CONTRATISTA_NUEVO = 'CONTRATISTA_NUEVO'
export const CONTRATISTA_ACTUALIZAR = 'CONTRATISTA_ACTUALIZAR'